### PR TITLE
Add ability to add bunnies!

### PR DESCRIPTION
**Pull request by doublej472**
Needs CSS fix bad, also needs ability to remove bunnies.

### CODE REVIEW

**Comment by doublej472** [comment]
@sladcikc after this is merged you should work on adding the ability to remove infants and breeders
@theshirkey you can help fix up CSS for this as well

**Comment by sladcikc** [comment]
Yeah I'm trying to view your branch rn

**Comment by doublej472** [comment]
@sladcikc If I merge this you can combine that into your current CSS pull request, getting 2 birds with 1 stone.

In the HTML I gave the inputs ID's that should make CSS a bit easier, but feel free to modify them as you need.

**Comment by sladcikc** [comment]
@doublej472 not my PR, but I say go for merge. I can't get your branch for some reason, so if something breaks we'll deal with it on master 😄

**Comment by doublej472** [comment]
@sladcikc messed up the names, whoops!

hopefully nothing terrible will happen :)

**Pull request merged**
