### PR TITLE
added remove to bunny/breeders || confirm on delete blog posts

### PR DESCRIPTION
**Pull request by sladcikc**
Needs CSS for the delete button for breeders and bunny detail pages

### CODE REVIEW

**Comment by doublej472** [comment]
Looks like something doesn't like it when I delete bunnies:

```
Found 16 babies.
Found 1 babies.
Found 1 babies.
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/home/doublej472/school/final-project-group-5/node_modules/bson/lib/bson/objectid.js:50:11)
    at Function.ObjectID (/home/doublej472/school/final-project-group-5/node_modules/bson/lib/bson/objectid.js:31:42)
    at /home/doublej472/school/final-project-group-5/server.js:95:61
    at Layer.handle [as handle_request] (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/layer.js:95:5)
    at /home/doublej472/school/final-project-group-5/node_modules/express/lib/router/index.js:281:22
    at param (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/index.js:354:14)
    at param (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/index.js:365:14)
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/home/doublej472/school/final-project-group-5/node_modules/bson/lib/bson/objectid.js:50:11)
    at Function.ObjectID (/home/doublej472/school/final-project-group-5/node_modules/bson/lib/bson/objectid.js:31:42)
    at /home/doublej472/school/final-project-group-5/server.js:95:61
    at Layer.handle [as handle_request] (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/layer.js:95:5)
    at /home/doublej472/school/final-project-group-5/node_modules/express/lib/router/index.js:281:22
    at param (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/index.js:354:14)
    at param (/home/doublej472/school/final-project-group-5/node_modules/express/lib/router/index.js:365:14)
5a2a45134b432c17b2592ddc
Found 15 babies.
```

**Comment by sladcikc** [comment]
You broke it D:

I don't get that error???

**Comment by doublej472** [comment]
really? one sec

It happens when I remove an infant

**Comment by doublej472** [comment]
Actually NVM, it looks like my test bunnies are breaking things

**Comment by doublej472** [comment]
I found it! the URL I specify is for a relative link, and this breaks the bunny getter, as it's translating to a link like this: 
```
http://127.0.0.1:3000/breeder/test
```
which nodejs complains about

**Comment by sladcikc** [comment]
ahh that will do it. It grabs the ID from the URL soooo

**Review by doublej472 — APPROVED** [review]

**Pull request merged**
